source 'https://rubygems.org'

gem 'rails', '3.2.14'

# gem 'sqlite3'

# Outside of :assets because we need the erb partials
gem 'analytics-js-rails', :path => '../..'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
end

gem 'jquery-rails'

group :development do
  gem 'thin'
end

group :test do
  gem 'rspec-rails'
end